name: Core

on:
  - push

env:
  php: 8.1

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            php: 8.1
          - os: windows-latest
            php: 8.2

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Running PHPUnit tests
        run: ./vendor/bin/phpunit tests
